config/routes.rb
Rails.application.routes.draw do
  root "projects#index"

  resources :projects do
    resources :tasks
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :tasks

    validates :name, presence: true
    validates :description, presence: true, length: { minimum: 6 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
        @projects = Project.all
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all 
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
     
    if @project.save
      redirect_to project_path(@project)
    else
      render :new, status: :unprocessable_entity
    end 
  end

  def edit 
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
  
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy 
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path, status: :see_other
  end

  private 
  
  def project_params
    params.require(:project).permit(:name, :description)
  end     
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    redirect_to project_path(@project)
  end
    
  private
  
  def task_params
    params.require(:task).permit(:description, :due_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with model: project do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% project.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% project.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form", project: @project %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<ul>
  <% @projects.each do |project| %>
    <li>
      <%= link_to project.name, project %>
    </li>
  <% end %>
</ul>
<%= link_to "New Project", new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render "form", project: @project %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<p><%= @project.description %></p>

<ul>
  <li><%= link_to "Edit", edit_project_path(@project) %></li>
  <li><%= link_to "Destroy", project_path(@project), data: { turbo_method: :delete, 
                                                         turbo_confirm: "Are you sure?"}
  %></li>
</ul>

<h2>Tasks</h2>
<% @project.tasks.each do |task| %>
  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>Task:</strong>
    <%= task.due_at %>
  </p>
<% end %>


<h2>Add a task:</h2>
<%= form_with model: [ @project, @project.tasks.build ] do |form| %>
  <p>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </p>
  <p>
    <%= form.label :due_at %><br>
    <%= form.text_area :due_at %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>